/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "emjirayzinkuksdcvsek"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtamlyYXl6aW5rdWtzZGN2c2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjA3NDEsImV4cCI6MjA3NDYzNjc0MX0.v4FYXqsQ61MS449uwsjxy2-WterjLoYmxsiJ4PD-I2I"